# docker-compose.yml

version: '3.8'

services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  hash_service:
    restart: always
    build:
      dockerfile: hash_service.Dockerfile
      context: ../unique-id-generator/
    command: uvicorn hash_service:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8001:8000"

  web_service:
    restart: always
    build:
      context: .
      dockerfile: shortener.Dockerfile
    volumes:
      - .:/home/app/web
      - shortener_static_volume:/home/app/web/static
    command: python3 manage.py runserver --noreload 0.0.0.0:8000
    ports:
      - "8000:8000"

  nginx:
    restart: always
    build: ./nginx/
    volumes:
      - ./nginx/www:/var/www:ro
      - ./nginx/sites-enabled/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro
      - ./nginx/protect:/etc/nginx/protect:ro
      - shortener_static_volume:/home/app/web/static
    ports:
      - "443:443"
      - "80:80"
    links:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/ssl-log:/var/log/letsencrypt
      - ./nginx/www/.well-known:/var/www/.well-known
    command: [
      "renew",
    ]

    links:
      - nginx

volumes:
  shortener_static_volume:
